// deno-lint-ignore-file no-explicit-any
/**
 * The li-sf CALIBRATION generator - moved out of the harness so the
 * harness is pair-AGNOSTIC (no engine imports).  Registered as the li-sf
 * pair's `calibrate` hook (mikmaq/transliterate-pairs.ts); the harness
 * reaches it only through spec.calibrate.
 *
 * Regenerate the calibration table: per-risk-band MEASURED accuracy of the
 * current li-sf rules on the TRAIN folds, VALIDATED on the holdout, plus
 * the branch-taken frequencies the ranked-candidate engine reads.  li-sf-
 * specific by nature: the risk markers and branch sites mirror
 * transliterate.ts internals.
 */
import { transliterateLiToSf, transliterateCandidates, transliterationRiskMarkers,
         TRANSLITERATOR_VERSION } from './transliterate.ts';
import { type CorpusPair } from './transliterate-pair.ts';
import { splitPairs } from './transliterate-harness.ts';

export function calibrateLiSf(allPairs: CorpusPair[]): void {
    const train = splitPairs(allPairs, 'train').pairs;
    const hold = splitPairs(allPairs, 'holdout').pairs;
    const bandOf = (p: CorpusPair) => {
        const m = transliterationRiskMarkers(p.source);
        return m.length === 0 ? 'clean' : m.join(',');
    };
    const measure = (pairs: CorpusPair[]) => {
        const bands = new Map<string, {n: number, ok: number}>();
        const singles = new Map<string, {n: number, ok: number}>();
        for(const p of pairs) {
            const ok = transliterateLiToSf(p.source) === p.target ? 1 : 0;
            const key = bandOf(p);
            const b = bands.get(key) ?? {n: 0, ok: 0};
            b.n++; b.ok += ok; bands.set(key, b);
            for(const m of transliterationRiskMarkers(p.source)) {
                const s1 = singles.get(m) ?? {n: 0, ok: 0};
                s1.n++; s1.ok += ok; singles.set(m, s1);
            }
        }
        return {bands, singles};
    };
    const t = measure(train);
    const cal: Record<string, {n: number, accuracy: number}> = {};
    for(const [key, b] of t.bands)
        if(key === 'clean' || b.n >= 10)
            cal[key] = {n: b.n, accuracy: Math.round(b.ok * 1000 / b.n) / 1000};
    for(const [m, s1] of t.singles)
        if(!(m in cal))
            cal[m] = {n: s1.n, accuracy: Math.round(s1.ok * 1000 / s1.n) / 1000};

    // Mine the BRANCH PROBABILITIES for the ranked-candidate engine: for
    // every branch site in every train pair, did the human's sf TAKE the
    // branch?  Keys mirror transliterate.ts branchSites().
    const branchProbs: Record<string, {taken: number, total: number}> = {};
    const bump = (key: string, taken: boolean) => {
        const e = branchProbs[key] ??= {taken: 0, total: 0};
        e.total++; if(taken) e.taken++;
    };
    const LEX_WORD = /[^\s.,!?]+/g;
    for(const p of train) {
        let base = p.source.replace(LEX_WORD, w => w);   // exceptions don't matter for site mining
        base = base.replaceAll('g', 'k').replaceAll('G', 'K');
        const low = base.toLowerCase(), sfLow = p.target.toLowerCase();
        for(let i = 0; i + 1 < low.length; i++) {
            if('lnm'.includes(low[i]) && 'ptjk'.includes(low[i+1])) {
                const before = i === 0 ? '' : low[i-1];
                if(before === '' || /\s/.test(before) || before === "'") continue;
                bump(`cluster:${before}|${low[i]}|${low[i+1]}`,
                     sfLow.includes(low.slice(Math.max(0, i-1), i+1) + "'" + low[i+1]));
            }
        }
        // The -ei branch key splits by pos class (vai keeps -ei; see
        // transliterate.ts posClass) - mirror it here.
        const eiKey = `ei:${p.pos === 'vai' ? 'vai' : p.pos === 'vit' ? 'vit' : p.pos ? 'other' : ''}`;
        for(const _m of low.matchAll(/ei(?=[\s.,!?]|$)/g))
            bump(eiKey, /ey(?=[\s.,!?]|$)/.test(sfLow + ' '));
        for(const m of low.matchAll(/[ptks]'(?=[a-z])/g))
            bump(`schwa:${low[m.index!]}|${low[m.index! + 2]}`, sfLow.includes('î'));
    }

    const stamp = new Date().toISOString().slice(0, 10);
    const version = `${TRANSLITERATOR_VERSION}@${stamp}/${train.length}pairs`;
    const out = `/**
 * GENERATED by \`transliterate-harness.ts --calibrate\` — do not hand-edit
 * (re-run the harness after any rules or oracle change).  Each band is a
 * sorted risk-marker combination; \`accuracy\` is the MEASURED exact-match
 * rate of the current rules on the TRAIN folds of the oracle (holdout
 * validation is printed by the harness at generation time).
 */
export const CALIBRATION_VERSION = ${JSON.stringify(version)};
export const CALIBRATION: Record<string, {n: number, accuracy: number}> = ${
        JSON.stringify(cal, null, 4)};

/** Branch-taken frequencies per context site, for the ranked-candidate
 *  engine (transliterateCandidates).  Same generation run as CALIBRATION. */
export const BRANCH_PROBABILITIES: Record<string, {taken: number, total: number}> = ${
        JSON.stringify(branchProbs, null, 4)};
`;
    const path = new URL('./transliterate-calibration.ts', import.meta.url).pathname;
    Deno.writeTextFileSync(path, out);
    console.log(`calibration written to ${path} (${Object.keys(cal).length} bands, ` +
                `${Object.keys(branchProbs).length} branch contexts)`);
    // NOTE: transliterateCandidates reads BRANCH_PROBABILITIES imported at
    // process start - these rates evaluate the table that was IN EFFECT when
    // this run began.  After writing a fresh table (above), re-run
    // --calibrate once more to score it.
    console.log('\ntop-k candidate hit rates (holdout; using the table loaded at startup):');
    for(const k of [1, 2, 3, 5]) {
        const hit = hold.filter(p =>
            transliterateCandidates(p.source, k, {pos: p.pos}).some(c => c.text === p.target)).length;
        console.log(`  top-${k}: ${hit}/${hold.length} = ${(hit*100/hold.length).toFixed(1)}%`);
    }
    console.log(`\nholdout validation (calibrated vs actual):`);
    const h = measure(hold);
    for(const [key, b] of [...h.bands.entries()].sort((a, b2) => b2[1].n - a[1].n)) {
        if(b.n < 5) continue;
        const calAcc = cal[key]?.accuracy;
        const actual = b.ok / b.n;
        const drift = calAcc !== undefined ? Math.abs(actual - calAcc) : undefined;
        console.log(`  ${key.padEnd(40)} n=${String(b.n).padStart(4)} ` +
                    `calibrated=${calAcc !== undefined ? (calAcc*100).toFixed(0)+'%' : ' n/a'} ` +
                    `holdout=${(actual*100).toFixed(0)}%` +
                    (drift !== undefined && drift > 0.15 ? '   << DRIFT' : ''));
    }
}
