/**
 * GENERATED by `transliterate-harness.ts --calibrate` — do not hand-edit
 * (re-run the harness after any rules or oracle change).  Each band is a
 * sorted risk-marker combination; `accuracy` is the MEASURED exact-match
 * rate of the current rules on the TRAIN folds of the oracle (holdout
 * validation is printed by the harness at generation time).
 */
export const CALIBRATION_VERSION = "li-sf/rules-v2@2026-07-07/1236pairs";
export const CALIBRATION: Record<string, {n: number, accuracy: number}> = {
    "clean": {
        "n": 621,
        "accuracy": 0.857
    },
    "l-before-k": {
        "n": 60,
        "accuracy": 0.167
    },
    "schwa-cluster": {
        "n": 78,
        "accuracy": 0.846
    },
    "word-final-ei": {
        "n": 26,
        "accuracy": 0.577
    },
    "sonorant-cluster": {
        "n": 323,
        "accuracy": 0.712
    },
    "schwa-cluster,sonorant-cluster": {
        "n": 28,
        "accuracy": 0.357
    },
    "sonorant-cluster,ult": {
        "n": 47,
        "accuracy": 0.553
    },
    "l-before-k,sonorant-cluster": {
        "n": 10,
        "accuracy": 0.5
    },
    "ult": {
        "n": 54,
        "accuracy": 0.593
    },
    "lexical-exception": {
        "n": 18,
        "accuracy": 0.389
    }
};
